from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from tfx_quant.packaging import build_support as bs

_LOCK_SNIPPET = """\
#
# autogenerated
#
annotated-types==0.8.0 \\
    --hash=sha256:13b2beaad985e05e2d6407ee4c4f35590b11f8d693a258a561055cac8f64cab7 \\
    --hash=sha256:f072f4d804ea359e4eaf198b1af7a8b0943881a87f31bb764f8bf219bb9419e0
    # via pydantic
comtypes==1.4.16 \\
    --hash=sha256:cd66d1add01265cface4df51ba1e31cd1657e04463c281c802e737e79e1ba93c
    # via -r installer/requirements.in
"""


def test_sha256_and_verify(tmp_path: Path) -> None:
    f = tmp_path / "x.bin"
    f.write_bytes(b"hello")
    digest = hashlib.sha256(b"hello").hexdigest()
    assert bs.sha256_file(f) == digest
    bs.verify_sha256(f, digest.upper())  # case-insensitive
    with pytest.raises(bs.BuildError):
        bs.verify_sha256(f, "0" * 64)


def test_parse_requirements_lock() -> None:
    entries = bs.parse_requirements_lock(_LOCK_SNIPPET)
    assert [e["name"] for e in entries] == ["annotated-types", "comtypes"]
    assert entries[0]["version"] == "0.8.0"
    assert len(entries[0]["hashes"]) == 2
    assert len(entries[1]["hashes"]) == 1


def test_write_sha256sums(tmp_path: Path) -> None:
    stage = tmp_path / "app"
    (stage / "sub").mkdir(parents=True)
    (stage / "a.txt").write_text("a", encoding="utf-8")
    (stage / "sub" / "b.txt").write_text("b", encoding="utf-8")
    out = stage / "SHA256SUMS"
    count = bs.write_sha256sums(stage, out)
    assert count == 2
    lines = out.read_text(encoding="utf-8").splitlines()
    assert any(line.endswith("  a.txt") for line in lines)
    assert any(line.endswith("  sub/b.txt") for line in lines)
    assert not any("SHA256SUMS" in line for line in lines)


def test_license_inventory_and_text(tmp_path: Path) -> None:
    sp = tmp_path / "site-packages"
    di = sp / "wombat-1.2.3.dist-info"
    di.mkdir(parents=True)
    (di / "METADATA").write_text(
        "Name: wombat\nVersion: 1.2.3\nLicense: MIT\n\nbody\n", encoding="utf-8"
    )
    (di / "LICENSE").write_text("MIT text", encoding="utf-8")
    inventory = bs.collect_license_inventory(sp)
    assert inventory == [
        {"name": "wombat", "version": "1.2.3", "license": "MIT", "license_files": "LICENSE"}
    ]
    text = bs.render_license_text(inventory)
    assert "wombat 1.2.3 — MIT" in text
    assert "不隨本安裝檔散布" in text  # default: nothing proprietary bundled

    bundled = bs.render_license_text(inventory, vendor_bundled=True)
    assert "專有元件" in bundled and "散布之授權" in bundled
    assert "wombat 1.2.3 — MIT" in bundled


def test_copy_vendor_tree_filters_debug_and_docs(tmp_path: Path) -> None:
    src = tmp_path / "API"
    (src / "sub").mkdir(parents=True)
    for name in (
        "YuantaOrd.ocx",
        "YuantaOrdLib.dll",
        "install_YTFutOrdAP.bat",
        "msvcrtd.dll",  # debug CRT -> skipped
        "元大行情API.pdf",  # doc -> skipped
        "sample.py",  # -> skipped
        "sub/libns.dll",
    ):
        p = src / name
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(b"x")
    dest = tmp_path / "out"
    n = bs.copy_vendor_tree(src, dest)
    got = {p.relative_to(dest).as_posix() for p in dest.rglob("*") if p.is_file()}
    assert got == {
        "YuantaOrd.ocx",
        "YuantaOrdLib.dll",
        "install_YTFutOrdAP.bat",
        "sub/libns.dll",
    }
    assert n == 4


def test_copy_vendor_tree_missing_src_raises(tmp_path: Path) -> None:
    with pytest.raises(bs.BuildError):
        bs.copy_vendor_tree(tmp_path / "nope", tmp_path / "out")


def test_resolve_vcredist_offline_without_cache(tmp_path: Path) -> None:
    with pytest.raises(bs.BuildError):
        bs.resolve_vcredist(cache_dir=tmp_path, allow_download=False)


def test_resolve_vcredist_explicit_path_is_trusted(tmp_path: Path) -> None:
    p = tmp_path / "vc_redist.x86.exe"
    p.write_bytes(b"anything")
    assert bs.resolve_vcredist(cache_dir=tmp_path, explicit_path=p, allow_download=False) == p


def test_render_release_notes_substitutes_and_preserves_unknown() -> None:
    out = bs.render_release_notes(
        "v{{ version }} rev {{ source_revision }} extra {{ mystery }}",
        {"version": "0.1.0", "source_revision": "abc123"},
    )
    assert out == "v0.1.0 rev abc123 extra {{ mystery }}"


def test_rewrite_embed_pth(tmp_path: Path) -> None:
    runtime = tmp_path / "runtime"
    runtime.mkdir()
    pth = runtime / "python311._pth"
    pth.write_text("python311.zip\n.\n\n# import site\n", encoding="utf-8")
    bs.rewrite_embed_pth(runtime, ["..\\Lib\\site-packages", "..\\src"])
    lines = pth.read_text(encoding="utf-8").splitlines()
    assert "..\\Lib\\site-packages" in lines
    assert "..\\src" in lines
    assert lines[-1] == "import site"
    assert "# import site" not in lines


def test_rewrite_embed_pth_without_file_raises(tmp_path: Path) -> None:
    with pytest.raises(bs.BuildError):
        bs.rewrite_embed_pth(tmp_path, [])


def test_resolve_python_embed_zip_offline_without_cache(tmp_path: Path) -> None:
    with pytest.raises(bs.BuildError):
        bs.resolve_python_embed_zip(cache_dir=tmp_path, allow_download=False)


def test_resolve_python_embed_zip_uses_verified_cache(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    cache = tmp_path / "cache"
    cache.mkdir()
    zip_path = cache / f"python-{bs.EMBED_PYTHON_VERSION}-embed-win32.zip"
    zip_path.write_bytes(b"pretend-zip")
    monkeypatch.setattr(bs, "EMBED_PYTHON_SHA256", hashlib.sha256(b"pretend-zip").hexdigest())
    assert bs.resolve_python_embed_zip(cache_dir=cache, allow_download=False) == zip_path


def test_build_manifest_shape(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    stage = tmp_path / "app"
    stage.mkdir()
    (stage / "f.txt").write_text("x", encoding="utf-8")
    embed = tmp_path / "python-embed.zip"
    embed.write_bytes(b"zip")
    manifest = bs.build_manifest(
        app_version="0.1.0",
        source_revision="deadbeef",
        source_dirty=False,
        tools=bs.ToolVersions(python="3.11.9", pip="24.0"),
        python_embed_zip=embed,
        requirements_lock_text=_LOCK_SNIPPET,
        stage_dir=stage,
    )
    assert manifest["app_version"] == "0.1.0"
    assert manifest["source_revision"] == "deadbeef"
    assert manifest["python_embed"]["sha256"] == hashlib.sha256(b"zip").hexdigest()
    assert manifest["staged_file_count"] == 1
    assert manifest["vendor_bundle"] is None
    assert {d["name"] for d in manifest["dependencies"]} == {"annotated-types", "comtypes"}
    # must be JSON-serialisable
    json.dumps(manifest)


def test_build_manifest_records_vendor_bundle(tmp_path: Path) -> None:
    stage = tmp_path / "app"
    stage.mkdir()
    embed = tmp_path / "e.zip"
    embed.write_bytes(b"z")
    manifest = bs.build_manifest(
        app_version="0.1.0",
        source_revision="x",
        source_dirty=True,
        tools=bs.ToolVersions(python="3.11.9", pip="24.0"),
        python_embed_zip=embed,
        requirements_lock_text="",
        stage_dir=stage,
        vendor_bundle={
            "redistribution_right_asserted_by_distributor": True,
            "yuanta_trade_api": {},
        },
    )
    assert manifest["vendor_bundle"]["redistribution_right_asserted_by_distributor"] is True
    json.dumps(manifest)


def test_make_release_manifest(tmp_path: Path) -> None:
    exe = tmp_path / "tfx-quant-setup-0.1.0.exe"
    exe.write_bytes(b"MZ...")
    stage_manifest = {"app_version": "0.1.0", "source_revision": "abc", "source_dirty": False}
    rel = bs.make_release_manifest(
        installer_path=exe,
        stage_build_manifest=stage_manifest,
        signed=False,
        signature_subject=None,
    )
    assert rel["installer"]["filename"] == "tfx-quant-setup-0.1.0.exe"
    assert rel["installer"]["sha256"] == hashlib.sha256(b"MZ...").hexdigest()
    assert rel["signature"] == {"signed": False, "subject": None}
    assert rel["app_version"] == "0.1.0"


def test_resolve_source_revision_on_this_repo() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    commit, dirty = bs.resolve_source_revision(repo_root)
    assert len(commit) == 40 or commit == "unknown"
    assert isinstance(dirty, bool)
